import { useState, useEffect, useRef } from "react";
import { getSocket } from "./socket";
import { useSocketConnected } from "./WorkspaceSocketProvider";

export function chatPanel({ workspaceId }) {
  const connected = useSocketConnected();
  const [messages, setMessages] = useState([]);
  const [question, setQuestion] = useState("");
  const [streaming, setStreaming] = useState(false);
  const [error, setError] = useState("");
  const assistantId = useRef(null);

  //run this useffect when the workspace id changes

  // why not store the workspaceid in workspace store and use it here instead of passing it as a prop
  //
  useEffect(() => {
    if (!workspaceId) return;
    const socket = getSocket();

    function loadHistory() {
      socket.emit("chat:history", { workspaceId });
    }

    //store the message in the state when the message event is received from the server
    function handleHistory({ messages: history }) {
      setMessages(
        history.map((msg) => {
          return {
            id: msg.id,
            role: msg.role,
            content: msg.content,
            citations: msg.sources ?? [],
          };
        }),
      );
    }

    function handleStart() {
      setStreaming(true);
      setError("");
    }

    function handleMetadata(metadata) {
      const id = assistantId.current;
      if (!id) return;

      setMessages((current) =>
        current.map((message) =>
          message.id === id
            ? {
                ...message,
                citations: metadata.citations ?? [],
                hasContradiction: metadata.hasContradiction,
                contradictions: metadata.contradictions ?? [],
                cached: metadata.cached,
                cacheSimilarity: metadata.cacheSimilarity,
                reason: metadata.reason,
              }
            : message,
        ),
      );
    }

    //token here means the answer generated by the llm in streaming mode
    function handleToken({ token }) {
      const id = assistantId.current;
      if (!id) return;
      setMessages((current) =>
        current.map((message) =>
          message.id === id
            ? {
                ...message,
                content: message.content + token,
              }
            : message,
        ),
      );
    }

    function handleDone({ answer, citations }) {
      const id = assistantId.current;

      setMessages((message) =>
        message.map((msg) =>
          msg.id === id
            ? {
                ...msg,
                content: answer,
                citations: citations ?? msg.citations,
                streaming: false,
              }
            : msg,
        ),
      );

        setStreaming(false);
        assistantId.current = null
    }

    function handleError(payload){
        setError(
            payload?.message ||
          payload?.messages ||
          "The chat request failed.",
        )

         const id = assistantId.current;
      if (id) {
        setMessages((current) =>
          current.filter(
            (message) =>
              message.id !== id || message.content.length > 0,
          ),
        );
      }

      assistantId.current = null;
      setStreaming(false);
    }

    //these are all the events which frontend listens and handles
    socket.on('connect', loadHistory)
    socket.on('chat:history:load', loadHistory);
    socket.on('chat:start',handleStart)
    socket.on("chat:metadata", handleMetadata);
    socket.on("chat:token", handleToken);
    socket.on("chat:done", handleDone);
    socket.on("chat:error", handleError);

     if (socket.connected) {
      loadHistory();
    }
     return () => {
      socket.off("connect", loadHistory);
      socket.off("chat:history:load", handleHistory);
      socket.off("chat:start", handleStart);
      socket.off("chat:metadata", handleMetadata);
      socket.off("chat:token", handleToken);
      socket.off("chat:done", handleDone);
      socket.off("chat:error", handleError);
    };
  }, [workspaceId]);

  function sendQuestion(event){
    event.preventDefault()

    const trimmedQuestion = question.trim()
    if(!trimmedQuestion || !workspaceId || !connected || streaming){
        return
    }

    const nextAssistantId = crypto.randomUUID()
    assistantId.current= nextAssistantId
    setError('')

    //u store ur question message and store the ref of the next upcoming msg as nextassistant id its content ,role ,citation,streaming which is true
    setMessages((current) => [
      ...current,
      {
        id: crypto.randomUUID(),
        role: "USER",
        content: trimmedQuestion,
        citations: [],
      },
      {
        id: nextAssistantId,
        role: "ASSISTANT",
        content: "",
        citations: [],
        streaming: true,
      },
    ]);

    setQuestion("")

    //start it
    socket.emit('chat:message', {
        question:trimmedQuestion,
        workspaceId
    })
  }

  function clearChat(){
    if(!workspaceId || streaming){
        return
    }

    //backend listens this event to whole workspace chat
    socket.emit('chat:clear', {workspaceId})
    setMessages([])
    setError('')
  }

  return (
    <section>
      <header>
        <h2>Chat</h2>
        <span>{connected ? "Connected" : "Connecting..."}</span>
        <button
          type="button"
          onClick={clearChat}
          disabled={!connected || streaming || messages.length === 0}
        >
          Clear chat
        </button>
      </header>

      <div aria-live="polite">
        {messages.map((message) => (
          <article key={message.id}>
            <h3>
              {message.role === "USER" ? "You" : "Assistant"}
              {message.cached && " · Cached"}
              {message.streaming && " · Generating"}
            </h3>

            <p>{message.content || (message.streaming ? "…" : "")}</p>

            {message.cacheSimilarity != null && (
              <p>
                Cache similarity:{" "}
                {message.cacheSimilarity}
              </p>
            )}

            {message.hasContradiction &&
              message.contradictions?.map((item, index) => (
                <p key={index} role="note">
                  Conflicting information detected: {item.topic}
                </p>
              ))}

            {message.citations?.length > 0 && (
              <details>
                <summary>Sources ({message.citations.length})</summary>
                <ul>
                  {message.citations.map((citation, index) => (
                    <li key={citation.id ?? index}>
                      <a
                        href={citation.pageUrl}
                        target="_blank"
                        rel="noreferrer"
                      >
                        {citation.pageTitle || citation.pageUrl}
                      </a>
                      {citation.sectionHeading &&
                        ` · ${citation.sectionHeading}`}
                    </li>
                  ))}
                </ul>
              </details>
            )}
          </article>
        ))}
      </div>

      {error && <p role="alert">{error}</p>}

      <form onSubmit={sendQuestion}>
        <label htmlFor="chat-question">Ask a question</label>
        <textarea
          id="chat-question"
          value={question}
          onChange={(event) => setQuestion(event.target.value)}
          disabled={!connected || streaming}
          required
        />
        <button
          type="submit"
          disabled={!connected || streaming || !question.trim()}
        >
          {streaming ? "Answering..." : "Send"}
        </button>
      </form>
    </section>
  );
}
