import { useState, useEffect, useRef } from "react";
import { getSocket } from "../../realtime/socket";
import { useSocketConnected } from "../../realtime/WorkspaceSocketProvider";

export default function ChatPanel({ workspaceId }) {
  const connected = useSocketConnected();
  const [messages, setMessages] = useState([]);
  const [question, setQuestion] = useState("");
  const [streaming, setStreaming] = useState(false);
  const [error, setError] = useState("");
  const assistantId = useRef(null);
  const messagesEndRef = useRef(null);

  //run this useffect when the workspace id changes

  // why not store the workspaceid in workspace store and use it here instead of passing it as a prop
  //
  useEffect(() => {
    if (!workspaceId) return;

    setMessages([]);
    setStreaming(false);
    setError("");
    assistantId.current = null;

    const socket = getSocket();

    function loadHistory() {
      socket.emit("chat:history", { workspaceId });
    }

    //store the message in the state when the message event is received from the server
    function handleHistory({ messages: history }) {
      setMessages(
        history.map((msg) => {
          return {
            id: msg.id,
            role: msg.role,
            content: msg.content,
            citations: msg.sources ?? [],
          };
        }),
      );
    }

    function handleStart() {
      setStreaming(true);
      setError("");
    }

    function handleMetadata(metadata) {
      const id = assistantId.current;
      if (!id) return;

      setMessages((current) =>
        current.map((message) =>
          message.id === id
            ? {
                ...message,
                citations: metadata.citations ?? [],
                hasContradiction: metadata.hasContradiction,
                contradictions: metadata.contradictions ?? [],
                cached: metadata.cached,
                cacheSimilarity: metadata.cacheSimilarity,
                reason: metadata.reason,
              }
            : message,
        ),
      );
    }

    //token here means the answer generated by the llm in streaming mode
    function handleToken({ token }) {
      const id = assistantId.current;
      if (!id) return;
      setMessages((current) =>
        current.map((message) =>
          message.id === id
            ? {
                ...message,
                content: message.content + token,
              }
            : message,
        ),
      );
    }

    function handleDone({ answer, citations }) {
      const id = assistantId.current;

      setMessages((message) =>
        message.map((msg) =>
          msg.id === id
            ? {
                ...msg,
                content: answer,
                citations: citations ?? msg.citations,
                streaming: false,
              }
            : msg,
        ),
      );

        setStreaming(false);
        assistantId.current = null
    }

    function handleError(payload){
        setError(
            payload?.message ||
          payload?.messages ||
          "The chat request failed.",
        )

         const id = assistantId.current;
      if (id) {
        setMessages((current) =>
          current.filter(
            (message) =>
              message.id !== id || message.content.length > 0,
          ),
        );
      }

      assistantId.current = null;
      setStreaming(false);
    }

    //these are all the events which frontend listens and handles
    socket.on('connect', loadHistory)
    socket.on('chat:history:load', handleHistory);
    socket.on('chat:start',handleStart)
    socket.on("chat:metadata", handleMetadata);
    socket.on("chat:token", handleToken);
    socket.on("chat:done", handleDone);
    socket.on("chat:error", handleError);

     if (socket.connected) {
      loadHistory();
    }
     return () => {
      socket.off("connect", loadHistory);
      socket.off("chat:history:load", handleHistory);
      socket.off("chat:start", handleStart);
      socket.off("chat:metadata", handleMetadata);
      socket.off("chat:token", handleToken);
      socket.off("chat:done", handleDone);
      socket.off("chat:error", handleError);
    };
  }, [workspaceId]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  function sendQuestion(event){
    event.preventDefault()

    const trimmedQuestion = question.trim()
    if(!trimmedQuestion || !workspaceId || !connected || streaming){
        return
    }

    const nextAssistantId = crypto.randomUUID()
    assistantId.current= nextAssistantId
    setError('')

    //u store ur question message and store the ref of the next upcoming msg as nextassistant id its content ,role ,citation,streaming which is true
    setMessages((current) => [
      ...current,
      {
        id: crypto.randomUUID(),
        role: "USER",
        content: trimmedQuestion,
        citations: [],
      },
      {
        id: nextAssistantId,
        role: "ASSISTANT",
        content: "",
        citations: [],
        streaming: true,
      },
    ]);

    setQuestion("")

    //start it
    getSocket().emit('chat:message', {
        question:trimmedQuestion,
        workspaceId
    })
  }

  function clearChat(){
    if(!workspaceId || streaming){
        return
    }

    //backend listens this event to whole workspace chat
    getSocket().emit('chat:clear', {workspaceId})
    setMessages([])
    setError('')
  }

  return (
    <section className="chat-panel" aria-labelledby="workspace-chat-title">
      <header className="chat-panel__header">
        <div>
          <h2 id="workspace-chat-title">Workspace chat</h2>
          <p>Ask questions about indexed sources in this workspace.</p>
        </div>
        <div className="chat-panel__actions">
          <span role="status">{connected ? "Connected" : "Connecting..."}</span>
        <button
          type="button"
          onClick={clearChat}
          disabled={!connected || streaming || messages.length === 0}
        >
          Clear chat
        </button>
        </div>
      </header>

      <div
        className="chat-panel__messages"
        aria-live="polite"
        aria-busy={streaming}
      >
        {messages.length === 0 && (
          <p className="chat-panel__empty">No messages yet.</p>
        )}
        {messages.map((message) => (
          <article
            key={message.id}
            className={`chat-message chat-message--${message.role.toLowerCase()}`}
          >
            <h3 className="chat-message__role">
              {message.role === "USER" ? "You" : "Assistant"}
              {message.cached && " · Cached"}
              {message.streaming && " · Generating"}
            </h3>

            <p>{message.content || (message.streaming ? "Generating answer..." : "")}</p>

            {message.cacheSimilarity != null && (
              <p>
                Cache similarity:{" "}
                {message.cacheSimilarity}
              </p>
            )}

            {message.hasContradiction &&
              message.contradictions?.map((item, index) => (
                <p key={index} role="note">
                  Conflicting information detected: {item.topic}
                </p>
              ))}

            {message.citations?.length > 0 && (
              <details>
                <summary>Sources ({message.citations.length})</summary>
                <ul>
                  {message.citations.map((citation, index) => (
                    <li key={citation.id ?? index}>
                      <a
                        href={citation.pageUrl}
                        target="_blank"
                        rel="noreferrer"
                      >
                        {citation.pageTitle || citation.pageUrl}
                      </a>
                      {citation.sectionHeading &&
                        ` · ${citation.sectionHeading}`}
                    </li>
                  ))}
                </ul>
              </details>
            )}
          </article>
        ))}
        <div ref={messagesEndRef} />
      </div>

      {error && <p role="alert">{error}</p>}

      <form className="chat-panel__form" onSubmit={sendQuestion}>
        <label htmlFor="chat-question">Ask a question</label>
        <textarea
          id="chat-question"
          value={question}
          onChange={(event) => setQuestion(event.target.value)}
          disabled={!connected || streaming}
          placeholder="Ask about your indexed sources..."
          required
        />
        <button
          type="submit"
          disabled={!connected || streaming || !question.trim()}
        >
          {streaming ? "Answering..." : "Send"}
        </button>
      </form>
    </section>
  );
}
